### ISSUE TITLE
Active characters in Arabextex in standard footnotes

### ISSUE THREAD

**Issue by Conicsections** [fc7/arabxetex#1]
Active characters such as ^ and _ are not being treated as inactive within the \textarab{} environment when they this occurs in a \footnote{}. The package bigfoot solves this problem, but it is incompatible with ednotes. There is no problem within the \Anote, \Bnote, etc of ednotes.

Please see minimal file below.

Best,

Nathan

--------------------------

\documentclass[12pt,a4paper,twoside]{memoir}

\usepackage{bidi}
\usepackage{xltxtra}

\setmainfont[Mapping=tex-text]{Junicode}
\usepackage[novoc,fdf2noalif]{arabxetex}
\newfontinstance\arabicfont[Script=Arabic,Scale=1.2,WordSpace=2]{Scheherazade}

\begin{document}

Some English text with footnotes, some of which have some Arabic text in them:
 
Ladidada...We will have a footnote that contains the word \textarab{al-^skl} it is the \^ \ in the asci input of \textarab{^s} that causes the problem. It is being read as an operator in an uncalled math environment.\footnote{\textarab{al-^skl}.}

\end{document}

**Comment by fc7** [comment]
Solved with release 1.2.0
