### ISSUE TITLE
new language (n'ko) support

### ISSUE THREAD

**Issue by ckairaba** [fc7/arabxetex#3]
Is it possible to add N'ko language support in ArabxeTex ?
N'ko is RTL language like Arabic.
Here are some links :
http://en.wikipedia.org/wiki/N%27Ko_alphabet
http://www.kanjamadi.com/
http://www.unicode.org/charts/PDF/U07C0.pdf

**Comment by fc7** [comment]
Yes this is generally possible and I have made some positive tests with N'ko some years ago. But this out of the scope of ArabXeTeX. Please make a request for adding support in [polyglossia](https://github.com/reutenauer/polyglossia/issues) instead. If you need support for some form of alternative input convention (like with ArabXeTeX) then maybe a separate package would be appropriate.
