### ISSUE TITLE
bug in new ArabXeTeX distributed with MacTeX 2016

### ISSUE THREAD

**Issue by amroberts1** [fc7/arabxetex#6]
I've just [posted about it on stackexchange](https://tex.stackexchange.com/questions/317175/how-can-i-correct-for-a-bug-in-arabxetex-that-causes-problems-in-left-to-right-t) but thought I should also mention here that the new ArabXeTeX seems to have a bug that produces problems not in Arabic text but in left-to-right text. (See my post for MWE.)

**Comment by fc7** [comment]
As I mentioned on SE, this appears to be a bug in bidi, so nothing I can do here. You can find a workaround here: http://tex.stackexchange.com/questions/312874/polyglossia-or-bidi-bug-d-gets-inverted-to-d

**Comment by amroberts1** [comment]
Thank you for the clarification. I will submit the bug report to `bidi` (if
it hasn't been done already).
